# Start Mongo DB with the command 'docker-compose up -d'

services:
  mongodb:
    container_name: mongo
    image: mongo:4.2.18
    ports:
      - "27017:27017" # <host port>:<container port>
    volumes:
      - ./database:/data/db
    command: mongod
    logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '10'
    restart: always
